# Version de la syntaxe Docker Compose
version: '3.8'

services:
  # On définit notre service web ( application React)
  web:
    # construire l'image à partir du Dockerfile 
    build: .
    # On relie le port PC au port du conteneur
    ports:
      - "5173:5173"
    #  volumes permettent synchroniser code en temps réel
    volumes:
      - .:/app
      - /app/node_modules
    # On définit les variables d'environnement 
    environment:
      - NODE_ENV=development