services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true

  api:
    build: ./api
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./api/.env
    depends_on:
      - db-sql
      - db-nosql

  db-sql:
    image: mysql:8
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: gamerent_db
    volumes:
      - ./api/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-sql-data:/var/lib/mysql

  db-nosql:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-nosql-data:/data/db

volumes:
  db-sql-data:
  db-nosql-data: